Update v0.3 Default Pins
noisymime/speeduino pull request #663
Opened 2021-09-18 21:18 UTC by DetonationEMS

Add Barometric Pressure sensor and Vehicle Speed Sensor default pins to v0.3x

2021-09-20 09:33 UTC, diy-efi requested changes
Remove one of the pin definition lines.

2021-09-20 09:33 UTC, diy-efi commented on speeduino/init.ino
> +      pinBaro = A5; //Baro Sensor Input
You are adding pinBaro (A5) twice, here (Line 1270) and again later on (Line 1291).

2023-01-08 14:59 UTC, DeionSi commented
These changes are already in master. Commits d5fc16d and be58be3.

2023-01-23 22:06 UTC, DetonationEMS commented
Leaning to pull from VSCode. Didn't mean to re-open this. Sorry.

2023-01-23 22:06 UTC, closed without merging